FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

WORKDIR /app

COPY trainer/xception-trainer/requirements/preprocess.txt .
RUN pip install --no-cache-dir -r preprocess.txt

COPY trainer/base/ .


CMD ["python", "-u", "base_preprocess_consumer.py"]