FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

WORKDIR /app

COPY trainer/xception-trainer/requirements/preprocess.txt .
RUN pip install --no-cache-dir -r preprocess.txt

COPY trainer/base/ .
COPY trainer/xception-trainer/preprocess_consumer.py .

CMD ["python", "-u", "preprocess_consumer.py"]