name: Build and Push to Harbor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t 100.112.196.74:30002/mlops-core/test-app:latest .

      - name: Login to Harbor
        run: docker login 100.112.196.74:30002 -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}

      - name: Push to Harbor
        run: docker push 100.112.196.74:30002/mlops-core/test-app:latest